#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BFL_DebugFunction

#include "Basic.hpp"

#include "EN_DebugTag_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BFL_DebugFunction.BFL_DebugFunction_C
// 0x0000 (0x0028 - 0x0028)
class UBFL_DebugFunction_C final : public UBlueprintFunctionLibrary
{
public:
	static void GetAimAngleOutLogSetting(class UObject* __WorldContext, bool* AimAngleOutLog);
	static void GetFireTraceSetting(class UObject* __WorldContext, bool* FireTrace, bool* BulletSpeed);
	static void GetDebugLogSetting(class UObject* __WorldContext, struct FStr_DebugLogSetting* DebugLogSetting);
	static void SimpleDebugLog(const struct FStr_DebugLogSetting& DebugLogSetting, const class FString& InString, EN_DebugTag DebugTag, float Duration, const class FName Key, class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BFL_DebugFunction_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BFL_DebugFunction_C")
	}
	static class UBFL_DebugFunction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBFL_DebugFunction_C>();
	}
};
DUMPER7_ASSERTS_UBFL_DebugFunction_C;

}

