#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_556x45mm_FMJ

#include "Basic.hpp"

#include "BP_AmmoBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_556x45mm_FMJ.BP_556x45mm_FMJ_C
// 0x0000 (0x0488 - 0x0488)
class ABP_556x45mm_FMJ_C final : public ABP_AmmoBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_556x45mm_FMJ_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_556x45mm_FMJ_C")
	}
	static class ABP_556x45mm_FMJ_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_556x45mm_FMJ_C>();
	}
};
DUMPER7_ASSERTS_ABP_556x45mm_FMJ_C;

}

