#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DoorBase

#include "Basic.hpp"

#include "BP_DoorBase_classes.hpp"
#include "BP_DoorBase_parameters.hpp"


namespace SDK
{

// Function BP_DoorBase.BP_DoorBase_C.BndEvt__BP_DoorBase_office_doorB_K2Node_ComponentBoundEvent_3_ComponentHitSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_DoorBase_C::BndEvt__BP_DoorBase_office_doorB_K2Node_ComponentBoundEvent_3_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorBase_C", "BndEvt__BP_DoorBase_office_doorB_K2Node_ComponentBoundEvent_3_ComponentHitSignature__DelegateSignature");

	Params::BP_DoorBase_C_BndEvt__BP_DoorBase_office_doorB_K2Node_ComponentBoundEvent_3_ComponentHitSignature__DelegateSignature Parms{};

	Parms.HitComponent = HitComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DoorBase.BP_DoorBase_C.CloseDoor
// (BlueprintCallable, BlueprintEvent)

void ABP_DoorBase_C::CloseDoor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorBase_C", "CloseDoor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorBase.BP_DoorBase_C.ExecuteUbergraph_BP_DoorBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DoorBase_C::ExecuteUbergraph_BP_DoorBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorBase_C", "ExecuteUbergraph_BP_DoorBase");

	Params::BP_DoorBase_C_ExecuteUbergraph_BP_DoorBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DoorBase.BP_DoorBase_C.Interact
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   SelectIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DoorBase_C::Interact(class AActor* Actor, int32 SelectIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorBase_C", "Interact");

	Params::BP_DoorBase_C_Interact Parms{};

	Parms.Actor = Actor;
	Parms.SelectIndex = SelectIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DoorBase.BP_DoorBase_C.InteractInOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_DoorBase_C::InteractInOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorBase_C", "InteractInOverlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorBase.BP_DoorBase_C.InteractOutOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_DoorBase_C::InteractOutOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorBase_C", "InteractOutOverlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorBase.BP_DoorBase_C.OpenDoor
// (BlueprintCallable, BlueprintEvent)

void ABP_DoorBase_C::OpenDoor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorBase_C", "OpenDoor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorBase.BP_DoorBase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_DoorBase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorBase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorBase.BP_DoorBase_C.TL_DoorRotation__FinishedFunc
// (BlueprintEvent)

void ABP_DoorBase_C::TL_DoorRotation__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorBase_C", "TL_DoorRotation__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorBase.BP_DoorBase_C.TL_DoorRotation__UpdateFunc
// (BlueprintEvent)

void ABP_DoorBase_C::TL_DoorRotation__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorBase_C", "TL_DoorRotation__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

