#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FaceMaskBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "PhysicsCore_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FaceMaskBase.BP_FaceMaskBase_C
// 0x0010 (0x02B8 - 0x02A8)
class ABP_FaceMaskBase_C : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   FaceMask;                                          // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void BulletHitEvent(const struct FVector& HitLocation, const struct FVector& HitDirection, double HitDamage, double HitStunPower, double DoT_Damage, double DoT_Stun, double DoT_Time, double DoT_Interval, bool IsPenetrated, class FName HitBoneName, const struct FVector& AttackLocation, class AActor* ShooterActor, EPhysicalSurface HitSurfaceType, bool IsMultipleShot, class FName ShotID, class FName AmmoRowName);
	void DetachMask(bool IsHeadShot, int32 Hit, const struct FVector& HitDirection, const struct FVector& HitPosition);
	void DoTEvent(double Damage, double Stun, class FName AttackerRowName, class FName AmmoRowName);
	void ExecuteUbergraph_BP_FaceMaskBase(int32 EntryPoint);
	void Init_Tag();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FaceMaskBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FaceMaskBase_C")
	}
	static class ABP_FaceMaskBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FaceMaskBase_C>();
	}
};
DUMPER7_ASSERTS_ABP_FaceMaskBase_C;

}

