#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MeleeBase

#include "Basic.hpp"

#include "BP_MeleeBase_classes.hpp"
#include "BP_MeleeBase_parameters.hpp"


namespace SDK
{

// Function BP_MeleeBase.BP_MeleeBase_C.DestroyDamageArea
// (BlueprintCallable, BlueprintEvent)

void ABP_MeleeBase_C::DestroyDamageArea()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeBase_C", "DestroyDamageArea");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MeleeBase.BP_MeleeBase_C.ExecuteUbergraph_BP_MeleeBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MeleeBase_C::ExecuteUbergraph_BP_MeleeBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeBase_C", "ExecuteUbergraph_BP_MeleeBase");

	Params::BP_MeleeBase_C_ExecuteUbergraph_BP_MeleeBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MeleeBase.BP_MeleeBase_C.GetMeleeMotionState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EN_MeleeMotionState*                    MeleeMotionState_0                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MeleeBase_C::GetMeleeMotionState(EN_MeleeMotionState* MeleeMotionState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeBase_C", "GetMeleeMotionState");

	Params::BP_MeleeBase_C_GetMeleeMotionState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (MeleeMotionState_0 != nullptr)
		*MeleeMotionState_0 = Parms.MeleeMotionState_0;
}


// Function BP_MeleeBase.BP_MeleeBase_C.Init_CalcurateWeaponSpec
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_MeleeBase_C::Init_CalcurateWeaponSpec()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeBase_C", "Init_CalcurateWeaponSpec");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MeleeBase.BP_MeleeBase_C.MeleeAttack_End
// (BlueprintCallable, BlueprintEvent)

void ABP_MeleeBase_C::MeleeAttack_End()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeBase_C", "MeleeAttack_End");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MeleeBase.BP_MeleeBase_C.MeleeAttack_Start
// (BlueprintCallable, BlueprintEvent)

void ABP_MeleeBase_C::MeleeAttack_Start()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeBase_C", "MeleeAttack_Start");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MeleeBase.BP_MeleeBase_C.SetVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsVisible                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MeleeBase_C::SetVisibility(bool IsVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeBase_C", "SetVisibility");

	Params::BP_MeleeBase_C_SetVisibility Parms{};

	Parms.IsVisible = IsVisible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MeleeBase.BP_MeleeBase_C.SpawnDamageArea
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_MeleeBase_C::SpawnDamageArea()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeBase_C", "SpawnDamageArea");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MeleeBase.BP_MeleeBase_C.StartDelay
// (BlueprintCallable, BlueprintEvent)

void ABP_MeleeBase_C::StartDelay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeBase_C", "StartDelay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MeleeBase.BP_MeleeBase_C.UseWeapon
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsTriggerReleased                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MeleeBase_C::UseWeapon(bool IsTriggerReleased, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeBase_C", "UseWeapon");

	Params::BP_MeleeBase_C_UseWeapon Parms{};

	Parms.IsTriggerReleased = IsTriggerReleased;

	UObject::ProcessEvent(Func, &Parms);

	if (Success != nullptr)
		*Success = Parms.Success;
}

}

