#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MiniHole

#include "Basic.hpp"

#include "BP_MiniHole_classes.hpp"
#include "BP_MiniHole_parameters.hpp"


namespace SDK
{

// Function BP_MiniHole.BP_MiniHole_C.ExecuteUbergraph_BP_MiniHole
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MiniHole_C::ExecuteUbergraph_BP_MiniHole(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MiniHole_C", "ExecuteUbergraph_BP_MiniHole");

	Params::BP_MiniHole_C_ExecuteUbergraph_BP_MiniHole Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MiniHole.BP_MiniHole_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MiniHole_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MiniHole_C", "ReceiveTick");

	Params::BP_MiniHole_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MiniHole.BP_MiniHole_C.Show Under Box
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_MiniHole_C::Show_Under_Box()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MiniHole_C", "Show Under Box");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MiniHole.BP_MiniHole_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_MiniHole_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MiniHole_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

