#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MeleeDamageArea

#include "Basic.hpp"

#include "BP_MeleeDamageArea_classes.hpp"
#include "BP_MeleeDamageArea_parameters.hpp"


namespace SDK
{

// Function BP_MeleeDamageArea.BP_MeleeDamageArea_C.BndEvt__BP_MeleeDamageArea_DamageArea_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_MeleeDamageArea_C::BndEvt__BP_MeleeDamageArea_DamageArea_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeDamageArea_C", "BndEvt__BP_MeleeDamageArea_DamageArea_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_MeleeDamageArea_C_BndEvt__BP_MeleeDamageArea_DamageArea_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MeleeDamageArea.BP_MeleeDamageArea_C.CheckAlreadyHit
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           HitActor                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   IsNew                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MeleeDamageArea_C::CheckAlreadyHit(class AActor* HitActor, bool* IsNew)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeDamageArea_C", "CheckAlreadyHit");

	Params::BP_MeleeDamageArea_C_CheckAlreadyHit Parms{};

	Parms.HitActor = HitActor;

	UObject::ProcessEvent(Func, &Parms);

	if (IsNew != nullptr)
		*IsNew = Parms.IsNew;
}


// Function BP_MeleeDamageArea.BP_MeleeDamageArea_C.DestroyEvent
// (BlueprintCallable, BlueprintEvent)

void ABP_MeleeDamageArea_C::DestroyEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeDamageArea_C", "DestroyEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MeleeDamageArea.BP_MeleeDamageArea_C.ExecuteUbergraph_BP_MeleeDamageArea
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MeleeDamageArea_C::ExecuteUbergraph_BP_MeleeDamageArea(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeDamageArea_C", "ExecuteUbergraph_BP_MeleeDamageArea");

	Params::BP_MeleeDamageArea_C_ExecuteUbergraph_BP_MeleeDamageArea Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MeleeDamageArea.BP_MeleeDamageArea_C.InitializeDamageArea
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_MeleeDamageArea_C::InitializeDamageArea()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeDamageArea_C", "InitializeDamageArea");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MeleeDamageArea.BP_MeleeDamageArea_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_MeleeDamageArea_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MeleeDamageArea_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

