#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Nurse

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_NPCBase_classes.hpp"
#include "PhysicsCore_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Nurse.BP_Nurse_C
// 0x0010 (0x11B0 - 0x11A0)
class ABP_Nurse_C final : public ABP_NPCBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Nurse_C;                         // 0x11A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   faceMask_nurse;                                    // 0x11A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void BulletHitEvent(const struct FVector& HitLocation, const struct FVector& HitDirection, double HitDamage, double HitStunPower, double DoT_Damage, double DoT_Stun, double DoT_Time, double DoT_Interval, bool IsPenetrated, class FName HitBoneName, const struct FVector& AttackLocation, class AActor* ShooterActor, EPhysicalSurface HitSurfaceType, bool IsMultipleShot, class FName ShotID, class FName AmmoRowName);
	void ExecuteUbergraph_BP_Nurse(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Nurse_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Nurse_C")
	}
	static class ABP_Nurse_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Nurse_C>();
	}
};
DUMPER7_ASSERTS_ABP_Nurse_C;

}

