#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UIControllPawn

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_UIControllPawn.BP_UIControllPawn_C
// 0x0018 (0x0340 - 0x0328)
class ABP_UIControllPawn_C final : public APawn
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUIM_Results_C*                         ResultUI;                                          // 0x0338(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_UIControllPawn(int32 EntryPoint);
	void InpAxisKeyEvt_Gamepad_Right2D_K2Node_InputVectorAxisEvent_0(const struct FVector& AxisValue);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_UIControllPawn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_UIControllPawn_C")
	}
	static class ABP_UIControllPawn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_UIControllPawn_C>();
	}
};
DUMPER7_ASSERTS_ABP_UIControllPawn_C;

}

