#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_AiDepthScaner

#include "Basic.hpp"

#include "Str_Byte2D_structs.hpp"
#include "Str_ViewingAngle_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "Str_DepthScanCell_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_AiDepthScaner.BPC_AiDepthScaner_C
// 0x00C8 (0x0168 - 0x00A0)
class UBPC_AiDepthScaner_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FStr_ViewingAngle                      ViewingAngle;                                      // 0x00A8(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        ScanResolutionMultiply;                            // 0x00B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ScanRange;                                         // 0x00C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ScanDepthDeltaLimit;                               // 0x00C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 NPCMesh;                                           // 0x00D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TMap<struct FStr_Byte2D, struct FStr_DepthScanCell> DepthScanGrid;                               // 0x00D8(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FStr_Byte2D                            ScanResolution;                                    // 0x0128(0x0002)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12A[0x6];                                      // 0x012A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EObjectTypeQuery>                      LineTraceObjectTypes;                              // 0x0130(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	EDrawDebugTrace                               Draw_Debug_Type;                                   // 0x0140(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_141[0x3];                                      // 0x0141(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   EyeSocket;                                         // 0x0144(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CellConut_Up;                                      // 0x014C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CellConut_Left;                                    // 0x014D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14E[0x2];                                      // 0x014E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        DeltaAngleY;                                       // 0x0150(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DeltaAngleX;                                       // 0x0158(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DebugDeltaTime;                                    // 0x0160(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPC_AiDepthScaner(int32 EntryPoint);
	void InitializeDepthScan(class ABP_NPCBase_C* NPC_Actor);
	void ReceiveTick(float DeltaSeconds);
	void Scan(struct FVector* Focus_Location, bool* Success);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_AiDepthScaner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_AiDepthScaner_C")
	}
	static class UBPC_AiDepthScaner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_AiDepthScaner_C>();
	}
};
DUMPER7_ASSERTS_UBPC_AiDepthScaner_C;

}

