#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_DropItemMovement

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_DropItemMovement.BPC_DropItemMovement_C
// 0x0018 (0x00B8 - 0x00A0)
class UBPC_DropItemMovement_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        RotationSpeed;                                     // 0x00A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        ItemOrigin;                                        // 0x00B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPC_DropItemMovement(int32 EntryPoint);
	void PlayItemRotation(bool bEnabled);
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_DropItemMovement_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_DropItemMovement_C")
	}
	static class UBPC_DropItemMovement_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_DropItemMovement_C>();
	}
};
DUMPER7_ASSERTS_UBPC_DropItemMovement_C;

}

