#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_AiDepthScaner

#include "Basic.hpp"

#include "BPC_AiDepthScaner_classes.hpp"
#include "BPC_AiDepthScaner_parameters.hpp"


namespace SDK
{

// Function BPC_AiDepthScaner.BPC_AiDepthScaner_C.ExecuteUbergraph_BPC_AiDepthScaner
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_AiDepthScaner_C::ExecuteUbergraph_BPC_AiDepthScaner(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_AiDepthScaner_C", "ExecuteUbergraph_BPC_AiDepthScaner");

	Params::BPC_AiDepthScaner_C_ExecuteUbergraph_BPC_AiDepthScaner Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_AiDepthScaner.BPC_AiDepthScaner_C.InitializeDepthScan
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_NPCBase_C*                    NPC_Actor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPC_AiDepthScaner_C::InitializeDepthScan(class ABP_NPCBase_C* NPC_Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_AiDepthScaner_C", "InitializeDepthScan");

	Params::BPC_AiDepthScaner_C_InitializeDepthScan Parms{};

	Parms.NPC_Actor = NPC_Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_AiDepthScaner.BPC_AiDepthScaner_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_AiDepthScaner_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_AiDepthScaner_C", "ReceiveTick");

	Params::BPC_AiDepthScaner_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_AiDepthScaner.BPC_AiDepthScaner_C.Scan
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector*                         Focus_Location                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_AiDepthScaner_C::Scan(struct FVector* Focus_Location, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_AiDepthScaner_C", "Scan");

	Params::BPC_AiDepthScaner_C_Scan Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Focus_Location != nullptr)
		*Focus_Location = std::move(Parms.Focus_Location);

	if (Success != nullptr)
		*Success = Parms.Success;
}

}

