#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_PhysicalAnimationManager

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_PhysicalAnimationManager.BPC_PhysicalAnimationManager_C
// 0x00A0 (0x0140 - 0x00A0)
class UBPC_PhysicalAnimationManager_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USkeletalMeshComponent*                 Mesh;                                              // 0x00A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TMap<class FName, double>                     HitBones;                                          // 0x00B0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	double                                        TempAlpha;                                         // 0x0100(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECollisionEnabled                             PreCollisionType;                                  // 0x0108(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_109[0x7];                                      // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBPC_StateManager_C*                    StateManager;                                      // 0x0110(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           FootBoneNames;                                     // 0x0118(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance)
	class AALS_Base_CharacterBP_C*                BaseCharacter_BP;                                  // 0x0128(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           RagdollTimer;                                      // 0x0130(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsFootBone;                                        // 0x0138(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void HitReaction(const struct FVector& HitDirection, class FName HitBoneName);
	void ReceiveTick(float DeltaSeconds);
	void StartRagdoll_BPC();
	void Recover();
	void ExecuteUbergraph_BPC_PhysicalAnimationManager(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_PhysicalAnimationManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_PhysicalAnimationManager_C")
	}
	static class UBPC_PhysicalAnimationManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_PhysicalAnimationManager_C>();
	}
};
DUMPER7_ASSERTS_UBPC_PhysicalAnimationManager_C;

}

