#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_WeaponCustomManager

#include "Basic.hpp"

#include "BPC_WeaponCustomManager_classes.hpp"
#include "BPC_WeaponCustomManager_parameters.hpp"


namespace SDK
{

// Function BPC_WeaponCustomManager.BPC_WeaponCustomManager_C.OpenWeaponCustomUI
// (Public, BlueprintCallable, BlueprintEvent)

void UBPC_WeaponCustomManager_C::OpenWeaponCustomUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_WeaponCustomManager_C", "OpenWeaponCustomUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_WeaponCustomManager.BPC_WeaponCustomManager_C.SetupCustomManager
// (Public, BlueprintCallable, BlueprintEvent)

void UBPC_WeaponCustomManager_C::SetupCustomManager()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_WeaponCustomManager_C", "SetupCustomManager");

	UObject::ProcessEvent(Func, nullptr);
}

}

