#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Melee

#include "Basic.hpp"

#include "BPI_Melee_classes.hpp"
#include "BPI_Melee_parameters.hpp"


namespace SDK
{

// Function BPI_Melee.BPI_Melee_C.GetMeleeMotionState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EN_MeleeMotionState*                    MeleeMotionState                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_Melee_C::GetMeleeMotionState(EN_MeleeMotionState* MeleeMotionState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_Melee_C", "GetMeleeMotionState");

	Params::BPI_Melee_C_GetMeleeMotionState Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (MeleeMotionState != nullptr)
		*MeleeMotionState = Parms.MeleeMotionState;
}

}

