#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_InteractSystem

#include "Basic.hpp"

#include "BPI_InteractSystem_classes.hpp"
#include "BPI_InteractSystem_parameters.hpp"


namespace SDK
{

// Function BPI_InteractSystem.BPI_InteractSystem_C.Interact
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   SelectIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_InteractSystem_C::Interact(class AActor* Actor, int32 SelectIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_InteractSystem_C", "Interact");

	Params::BPI_InteractSystem_C_Interact Parms{};

	Parms.Actor = Actor;
	Parms.SelectIndex = SelectIndex;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function BPI_InteractSystem.BPI_InteractSystem_C.InteractInOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void IBPI_InteractSystem_C::InteractInOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_InteractSystem_C", "InteractInOverlay");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function BPI_InteractSystem.BPI_InteractSystem_C.InteractOutOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void IBPI_InteractSystem_C::InteractOutOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_InteractSystem_C", "InteractOutOverlay");

	AsUObject()->ProcessEvent(Func, nullptr);
}

}

