#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_PlayerObjectAction

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BPI_PlayerObjectAction.BPI_PlayerObjectAction_C.GetPlayerCameraPositionAndDirection
// 0x0038 (0x0038 - 0x0000)
struct BPI_PlayerObjectAction_C_GetPlayerCameraPositionAndDirection final
{
public:
	struct FVector                                position;                                          // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Direction;                                         // 0x0018(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CameraFOV;                                         // 0x0030(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_PlayerObjectAction_C_GetPlayerCameraPositionAndDirection;

// Function BPI_PlayerObjectAction.BPI_PlayerObjectAction_C.OBJ001_SetMovieOpacity
// 0x0010 (0x0010 - 0x0000)
struct BPI_PlayerObjectAction_C_OBJ001_SetMovieOpacity final
{
public:
	double                                        Opacity;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsNothing;                                         // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_PlayerObjectAction_C_OBJ001_SetMovieOpacity;

// Function BPI_PlayerObjectAction.BPI_PlayerObjectAction_C.OBJ003_SightControl
// 0x0018 (0x0018 - 0x0000)
struct BPI_PlayerObjectAction_C_OBJ003_SightControl final
{
public:
	double                                        CameraMoveIntensity;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Damage;                                            // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Entity;                                            // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_PlayerObjectAction_C_OBJ003_SightControl;

}

