#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_TaskItemSpawner

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_TaskItemSpawner.BPI_TaskItemSpawner_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_TaskItemSpawner_C final
{
public:
	void GetSpawnLocationAndSpotID(TMap<struct FVector, class FName>* SpawnData);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_TaskItemSpawner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_TaskItemSpawner_C")
	}
	static class IBPI_TaskItemSpawner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_TaskItemSpawner_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_TaskItemSpawner_C;

}

