#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_PaperTower

#include "Basic.hpp"

#include "BPI_PaperTower_classes.hpp"
#include "BPI_PaperTower_parameters.hpp"


namespace SDK
{

// Function BPI_PaperTower.BPI_PaperTower_C.SendMessageToPaperTower
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EN_PaperTowerMessage                    Message                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_PaperTower_C::SendMessageToPaperTower(EN_PaperTowerMessage Message)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_PaperTower_C", "SendMessageToPaperTower");

	Params::BPI_PaperTower_C_SendMessageToPaperTower Parms{};

	Parms.Message = Message;

	AsUObject()->ProcessEvent(Func, &Parms);
}

}

