#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Outline

#include "Basic.hpp"

#include "BPI_Outline_classes.hpp"
#include "BPI_Outline_parameters.hpp"


namespace SDK
{

// Function BPI_Outline.BPI_Outline_C.SetOutlineSetting
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    EnableOutline                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// Enum_Outline_Type                       Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_Outline_C::SetOutlineSetting(bool EnableOutline, Enum_Outline_Type Type)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_Outline_C", "SetOutlineSetting");

	Params::BPI_Outline_C_SetOutlineSetting Parms{};

	Parms.EnableOutline = EnableOutline;
	Parms.Type = Type;

	AsUObject()->ProcessEvent(Func, &Parms);
}

}

