#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_GunParts_Sight

#include "Basic.hpp"

#include "BPI_GunParts_Sight_classes.hpp"
#include "BPI_GunParts_Sight_parameters.hpp"


namespace SDK
{

// Function BPI_GunParts_Sight.BPI_GunParts_Sight_C.GetADSPoint
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USceneComponent**                 ADSPoint                                               (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void IBPI_GunParts_Sight_C::GetADSPoint(class USceneComponent** ADSPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_GunParts_Sight_C", "GetADSPoint");

	Params::BPI_GunParts_Sight_C_GetADSPoint Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (ADSPoint != nullptr)
		*ADSPoint = Parms.ADSPoint;
}


// Function BPI_GunParts_Sight.BPI_GunParts_Sight_C.GetSightCategory
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EN_GunParts_SightCategory*              SightCategory                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_GunParts_Sight_C::GetSightCategory(EN_GunParts_SightCategory* SightCategory)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_GunParts_Sight_C", "GetSightCategory");

	Params::BPI_GunParts_Sight_C_GetSightCategory Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (SightCategory != nullptr)
		*SightCategory = Parms.SightCategory;
}


// Function BPI_GunParts_Sight.BPI_GunParts_Sight_C.GetSightMagnification
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// double*                                 LensMagnificationFactor                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_GunParts_Sight_C::GetSightMagnification(double* LensMagnificationFactor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_GunParts_Sight_C", "GetSightMagnification");

	Params::BPI_GunParts_Sight_C_GetSightMagnification Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (LensMagnificationFactor != nullptr)
		*LensMagnificationFactor = Parms.LensMagnificationFactor;
}

}

