#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_ShootingTimer

#include "Basic.hpp"

#include "BPI_ShootingTimer_classes.hpp"


namespace SDK
{

// Function BPI_ShootingTimer.BPI_ShootingTimer_C.ShotCount
// (Public, BlueprintCallable, BlueprintEvent)

void IBPI_ShootingTimer_C::ShotCount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_ShootingTimer_C", "ShotCount");

	AsUObject()->ProcessEvent(Func, nullptr);
}

}

