#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_FocusLocator

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "EN_LocatorMoveMode_structs.hpp"


namespace SDK::Params
{

// Function BPI_FocusLocator.BPI_FocusLocator_C.GetCurrentFocusLocation
// 0x0018 (0x0018 - 0x0000)
struct BPI_FocusLocator_C_GetCurrentFocusLocation final
{
public:
	struct FVector                                FocusLocation;                                     // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_FocusLocator_C_GetCurrentFocusLocation;

// Function BPI_FocusLocator.BPI_FocusLocator_C.InitializeFocusLocator
// 0x0010 (0x0010 - 0x0000)
struct BPI_FocusLocator_C_InitializeFocusLocator final
{
public:
	double                                        BaseFocusSpeed;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 BrainActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_FocusLocator_C_InitializeFocusLocator;

// Function BPI_FocusLocator.BPI_FocusLocator_C.SendFocusData
// 0x0028 (0x0028 - 0x0000)
struct BPI_FocusLocator_C_SendFocusData final
{
public:
	struct FVector                                FocusTargetLocation;                               // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EN_LocatorMoveMode                            FocusMoveMode;                                     // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        FluctuationFactor;                                 // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_FocusLocator_C_SendFocusData;

// Function BPI_FocusLocator.BPI_FocusLocator_C.SetLookForwardMode
// 0x0001 (0x0001 - 0x0000)
struct BPI_FocusLocator_C_SetLookForwardMode final
{
public:
	bool                                          IsLookForwardMode;                                 // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_FocusLocator_C_SetLookForwardMode;

}

