#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_PlayerDebug

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "EN_DebugMode_structs.hpp"
#include "EN_Camera_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_PlayerDebug.BPI_PlayerDebug_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_PlayerDebug_C final
{
public:
	void GetDebugMode(EN_DebugMode* DebugMode);
	void SetDebugCameraMode(EN_Camera CameraPosition);
	void SetDebugMode(EN_DebugMode DebugMode);
	void SetDebugPlayerVisibility(bool IsVisible);
	void SetShootingTimer(class AActor* Timer, bool* Success);
	void SetSmoothCameraMove(bool Enable);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_PlayerDebug_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_PlayerDebug_C")
	}
	static class IBPI_PlayerDebug_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_PlayerDebug_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_PlayerDebug_C;

}

