#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_GunParts_LightAndLaser

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "EN_LightAndLaserDeviceMode_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_GunParts_LightAndLaser.BPI_GunParts_LightAndLaser_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_GunParts_LightAndLaser_C final
{
public:
	void ActivateDevice(bool IsPlayer);
	void DeactivateDevice(bool IsPlayer);
	void GetDeviceMode(EN_LightAndLaserDeviceMode* DeviceMode);
	void SetDeviceMalfunctionDownValue(double DownValue, bool IsPlayer);
	void SwitchDeviceMode(bool IsPlayer);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_GunParts_LightAndLaser_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_GunParts_LightAndLaser_C")
	}
	static class IBPI_GunParts_LightAndLaser_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_GunParts_LightAndLaser_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_GunParts_LightAndLaser_C;

}

