#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_NPC

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_NPC.BPI_NPC_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_NPC_C final
{
public:
	void Death(bool CountKill);
	void GetHeadLocation(struct FVector* HeadLocation);
	void GetNPCRowName(class FName* NPCRowName);
	void IsDown(bool* IsDown_0);
	void RefreshAITask();
	void StartRush();
	void WeaponLightControl(bool In, class AActor* LightONArea);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_NPC_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_NPC_C")
	}
	static class IBPI_NPC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_NPC_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_NPC_C;

}

