#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPItem

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ItemBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPItem.BPItem_C
// 0x0018 (0x0380 - 0x0368)
class ABPItem_C final : public ABP_ItemBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BPItem_C;                           // 0x0368(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           ResetTimer;                                        // 0x0378(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPItem(int32 EntryPoint);
	void ReceiveBeginPlay();
	void Reset();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPItem_C")
	}
	static class ABPItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPItem_C>();
	}
};
DUMPER7_ASSERTS_ABPItem_C;

}

