#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPLight_LongLamp_A_OFF

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPLight_LongLamp_A_OFF.BPLight_LongLamp_A_OFF_C.ExecuteUbergraph_BPLight_LongLamp_A_OFF
// 0x0004 (0x0004 - 0x0000)
struct BPLight_LongLamp_A_OFF_C_ExecuteUbergraph_BPLight_LongLamp_A_OFF final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPLight_LongLamp_A_OFF_C_ExecuteUbergraph_BPLight_LongLamp_A_OFF;

}

