#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTDecorator_IsDead

#include "Basic.hpp"

#include "AIModule_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTDecorator_IsDead.BTDecorator_IsDead_C
// 0x0010 (0x00B0 - 0x00A0)
class UBTDecorator_IsDead_C final : public UBTDecorator_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBPC_AiBrain_C*                         Ai_Brain;                                          // 0x00A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BTDecorator_IsDead(int32 EntryPoint);
	bool PerformConditionCheck(class AActor* OwnerActor);
	void ReceiveExecutionStartAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTDecorator_IsDead_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTDecorator_IsDead_C")
	}
	static class UBTDecorator_IsDead_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTDecorator_IsDead_C>();
	}
};
DUMPER7_ASSERTS_UBTDecorator_IsDead_C;

}

