#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CTask_ChamberAction

#include "Basic.hpp"

#include "CTask_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CTask_ChamberAction.CTask_ChamberAction_C
// 0x0000 (0x0030 - 0x0030)
class UCTask_ChamberAction_C final : public UCTask_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CTask_ChamberAction_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CTask_ChamberAction_C")
	}
	static class UCTask_ChamberAction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCTask_ChamberAction_C>();
	}
};
DUMPER7_ASSERTS_UCTask_ChamberAction_C;

}

