#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CTask_SearchEnemy

#include "Basic.hpp"

#include "CTask_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CTask_SearchEnemy.CTask_SearchEnemy_C
// 0x0000 (0x0030 - 0x0030)
class UCTask_SearchEnemy_C final : public UCTask_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CTask_SearchEnemy_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CTask_SearchEnemy_C")
	}
	static class UCTask_SearchEnemy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCTask_SearchEnemy_C>();
	}
};
DUMPER7_ASSERTS_UCTask_SearchEnemy_C;

}

