#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CTask_Focus

#include "Basic.hpp"

#include "CTask_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CTask_Focus.CTask_Focus_C
// 0x0000 (0x0030 - 0x0030)
class UCTask_Focus_C final : public UCTask_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CTask_Focus_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CTask_Focus_C")
	}
	static class UCTask_Focus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCTask_Focus_C>();
	}
};
DUMPER7_ASSERTS_UCTask_Focus_C;

}

