#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: electric_fan_SM

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass electric_fan_SM.electric_fan_SM_C
// 0x0028 (0x02D0 - 0x02A8)
class Aelectric_fan_SM_C final : public AActor
{
public:
	class UBoxComponent*                          Box3;                                              // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box2;                                              // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box1;                                              // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box;                                               // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM;                                                // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("electric_fan_SM_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"electric_fan_SM_C")
	}
	static class Aelectric_fan_SM_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Aelectric_fan_SM_C>();
	}
};
DUMPER7_ASSERTS_Aelectric_fan_SM_C;

}

