#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EN_GunPartsCategory

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EN_GunPartsCategory.EN_GunPartsCategory
// NumValues: 0x0010
enum class EN_GunPartsCategory : uint8
{
	NewEnumerator4                           = 0,
	NewEnumerator5                           = 1,
	NewEnumerator6                           = 2,
	NewEnumerator9                           = 3,
	NewEnumerator0                           = 4,
	NewEnumerator14                          = 5,
	NewEnumerator7                           = 6,
	NewEnumerator1                           = 7,
	NewEnumerator8                           = 8,
	NewEnumerator13                          = 9,
	NewEnumerator10                          = 10,
	NewEnumerator11                          = 11,
	NewEnumerator12                          = 12,
	NewEnumerator15                          = 13,
	NewEnumerator16                          = 14,
	EN_MAX                                   = 15,
};

}

