#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EN_ItemCategory

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EN_ItemCategory.EN_ItemCategory
// NumValues: 0x0008
enum class EN_ItemCategory : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	NewEnumerator5                           = 5,
	NewEnumerator6                           = 6,
	EN_MAX                                   = 7,
};

}

