#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EN_OnceItemEffects

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EN_OnceItemEffects.EN_OnceItemEffects
// NumValues: 0x0002
enum class EN_OnceItemEffects : uint8
{
	NewEnumerator0                           = 0,
	EN_MAX                                   = 1,
};

}

