#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HF_Stair

#include "Basic.hpp"

#include "LCBP_HomeFacilityBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HF_Stair.HF_Stair_C
// 0x0000 (0x03C0 - 0x03C0)
class AHF_Stair_C final : public ALCBP_HomeFacilityBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HF_Stair_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HF_Stair_C")
	}
	static class AHF_Stair_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHF_Stair_C>();
	}
};
DUMPER7_ASSERTS_AHF_Stair_C;

}

