#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUDP_Ammo

#include "Basic.hpp"

#include "HUDP_Ammo_classes.hpp"
#include "HUDP_Ammo_parameters.hpp"


namespace SDK
{

// Function HUDP_Ammo.HUDP_Ammo_C.RefreshIcon
// (Public, BlueprintCallable, BlueprintEvent)

void UHUDP_Ammo_C::RefreshIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDP_Ammo_C", "RefreshIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUDP_Ammo.HUDP_Ammo_C.SetAmmo
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   AmmoInChamber_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   AmmoInMagazine                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUDP_Ammo_C::SetAmmo(int32 AmmoInChamber_0, int32 AmmoInMagazine)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDP_Ammo_C", "SetAmmo");

	Params::HUDP_Ammo_C_SetAmmo Parms{};

	Parms.AmmoInChamber_0 = AmmoInChamber_0;
	Parms.AmmoInMagazine = AmmoInMagazine;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUDP_Ammo.HUDP_Ammo_C.SetFireMode
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EN_IconMode                             Safety                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EN_IconMode                             SemiAuto                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EN_IconMode                             FullAuto                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUDP_Ammo_C::SetFireMode(EN_IconMode Safety, EN_IconMode SemiAuto, EN_IconMode FullAuto)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDP_Ammo_C", "SetFireMode");

	Params::HUDP_Ammo_C_SetFireMode Parms{};

	Parms.Safety = Safety;
	Parms.SemiAuto = SemiAuto;
	Parms.FullAuto = FullAuto;

	UObject::ProcessEvent(Func, &Parms);
}

}

