#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUDP_Crosshair

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass HUDP_Crosshair.HUDP_Crosshair_C
// 0x0000 (0x02D0 - 0x02D0)
class UHUDP_Crosshair_C final : public UUserWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HUDP_Crosshair_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HUDP_Crosshair_C")
	}
	static class UHUDP_Crosshair_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHUDP_Crosshair_C>();
	}
};
DUMPER7_ASSERTS_UHUDP_Crosshair_C;

}

