#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUDP_Light

#include "Basic.hpp"

#include "HUDP_Light_classes.hpp"
#include "HUDP_Light_parameters.hpp"


namespace SDK
{

// Function HUDP_Light.HUDP_Light_C.RefreshIcon
// (Public, BlueprintCallable, BlueprintEvent)

void UHUDP_Light_C::RefreshIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDP_Light_C", "RefreshIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUDP_Light.HUDP_Light_C.SetLightMode
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EN_IconMode                             LightMode                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUDP_Light_C::SetLightMode(EN_IconMode LightMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDP_Light_C", "SetLightMode");

	Params::HUDP_Light_C_SetLightMode Parms{};

	Parms.LightMode = LightMode;

	UObject::ProcessEvent(Func, &Parms);
}

}

