#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LCBP_PlayerBox

#include "Basic.hpp"


namespace SDK::Params
{

// Function LCBP_PlayerBox.LCBP_PlayerBox_C.ExecuteUbergraph_LCBP_PlayerBox
// 0x0004 (0x0004 - 0x0000)
struct LCBP_PlayerBox_C_ExecuteUbergraph_LCBP_PlayerBox final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LCBP_PlayerBox_C_ExecuteUbergraph_LCBP_PlayerBox;

}

