#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LCBP_WaveCustom

#include "Basic.hpp"

#include "LCBP_WaveCustom_classes.hpp"
#include "LCBP_WaveCustom_parameters.hpp"


namespace SDK
{

// Function LCBP_WaveCustom.LCBP_WaveCustom_C.Body__FinishedFunc
// (BlueprintEvent)

void ALCBP_WaveCustom_C::Body__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WaveCustom_C", "Body__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_WaveCustom.LCBP_WaveCustom_C.Body__UpdateFunc
// (BlueprintEvent)

void ALCBP_WaveCustom_C::Body__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WaveCustom_C", "Body__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_WaveCustom.LCBP_WaveCustom_C.ExecuteUbergraph_LCBP_WaveCustom
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALCBP_WaveCustom_C::ExecuteUbergraph_LCBP_WaveCustom(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WaveCustom_C", "ExecuteUbergraph_LCBP_WaveCustom");

	Params::LCBP_WaveCustom_C_ExecuteUbergraph_LCBP_WaveCustom Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LCBP_WaveCustom.LCBP_WaveCustom_C.Interact
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   SelectIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALCBP_WaveCustom_C::Interact(class AActor* Actor, int32 SelectIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WaveCustom_C", "Interact");

	Params::LCBP_WaveCustom_C_Interact Parms{};

	Parms.Actor = Actor;
	Parms.SelectIndex = SelectIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LCBP_WaveCustom.LCBP_WaveCustom_C.InteractInOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void ALCBP_WaveCustom_C::InteractInOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WaveCustom_C", "InteractInOverlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_WaveCustom.LCBP_WaveCustom_C.InteractOutOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void ALCBP_WaveCustom_C::InteractOutOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WaveCustom_C", "InteractOutOverlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_WaveCustom.LCBP_WaveCustom_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ALCBP_WaveCustom_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WaveCustom_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_WaveCustom.LCBP_WaveCustom_C.WaveChange__FinishedFunc
// (BlueprintEvent)

void ALCBP_WaveCustom_C::WaveChange__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WaveCustom_C", "WaveChange__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_WaveCustom.LCBP_WaveCustom_C.WaveChange__UpdateFunc
// (BlueprintEvent)

void ALCBP_WaveCustom_C::WaveChange__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WaveCustom_C", "WaveChange__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_WaveCustom.LCBP_WaveCustom_C.WaveChangeFail__FinishedFunc
// (BlueprintEvent)

void ALCBP_WaveCustom_C::WaveChangeFail__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WaveCustom_C", "WaveChangeFail__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_WaveCustom.LCBP_WaveCustom_C.WaveChangeFail__UpdateFunc
// (BlueprintEvent)

void ALCBP_WaveCustom_C::WaveChangeFail__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WaveCustom_C", "WaveChangeFail__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

