#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LCBP_MonitorSwitchBase_R

#include "Basic.hpp"

#include "LCBP_MonitorSwitchBase_R_classes.hpp"
#include "LCBP_MonitorSwitchBase_R_parameters.hpp"


namespace SDK
{

// Function LCBP_MonitorSwitchBase_R.LCBP_MonitorSwitchBase_R_C.ExecuteUbergraph_LCBP_MonitorSwitchBase_R
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALCBP_MonitorSwitchBase_R_C::ExecuteUbergraph_LCBP_MonitorSwitchBase_R(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_MonitorSwitchBase_R_C", "ExecuteUbergraph_LCBP_MonitorSwitchBase_R");

	Params::LCBP_MonitorSwitchBase_R_C_ExecuteUbergraph_LCBP_MonitorSwitchBase_R Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LCBP_MonitorSwitchBase_R.LCBP_MonitorSwitchBase_R_C.Interact
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   SelectIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALCBP_MonitorSwitchBase_R_C::Interact(class AActor* Actor, int32 SelectIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_MonitorSwitchBase_R_C", "Interact");

	Params::LCBP_MonitorSwitchBase_R_C_Interact Parms{};

	Parms.Actor = Actor;
	Parms.SelectIndex = SelectIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LCBP_MonitorSwitchBase_R.LCBP_MonitorSwitchBase_R_C.InteractInOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void ALCBP_MonitorSwitchBase_R_C::InteractInOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_MonitorSwitchBase_R_C", "InteractInOverlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_MonitorSwitchBase_R.LCBP_MonitorSwitchBase_R_C.InteractOutOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void ALCBP_MonitorSwitchBase_R_C::InteractOutOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_MonitorSwitchBase_R_C", "InteractOutOverlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_MonitorSwitchBase_R.LCBP_MonitorSwitchBase_R_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ALCBP_MonitorSwitchBase_R_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_MonitorSwitchBase_R_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_MonitorSwitchBase_R.LCBP_MonitorSwitchBase_R_C.SetSwitchMode
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsActive                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALCBP_MonitorSwitchBase_R_C::SetSwitchMode(bool IsActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_MonitorSwitchBase_R_C", "SetSwitchMode");

	Params::LCBP_MonitorSwitchBase_R_C_SetSwitchMode Parms{};

	Parms.IsActive = IsActive;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LCBP_MonitorSwitchBase_R.LCBP_MonitorSwitchBase_R_C.SetUIText
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FStr_InteractUIText>&     InteractUIText_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ALCBP_MonitorSwitchBase_R_C::SetUIText(TArray<struct FStr_InteractUIText>& InteractUIText_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_MonitorSwitchBase_R_C", "SetUIText");

	Params::LCBP_MonitorSwitchBase_R_C_SetUIText Parms{};

	Parms.InteractUIText_0 = std::move(InteractUIText_0);

	UObject::ProcessEvent(Func, &Parms);

	InteractUIText_0 = std::move(Parms.InteractUIText_0);
}

}

