#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LCBP_YellowSign_WaveCustom

#include "Basic.hpp"

#include "LCBP_YellowSign_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LCBP_YellowSign_WaveCustom.LCBP_YellowSign_WaveCustom_C
// 0x0008 (0x0380 - 0x0378)
class ALCBP_YellowSign_WaveCustom_C final : public ALCBP_YellowSign_C
{
public:
	class UStaticMeshComponent*                   roadCones_A1;                                      // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LCBP_YellowSign_WaveCustom_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LCBP_YellowSign_WaveCustom_C")
	}
	static class ALCBP_YellowSign_WaveCustom_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALCBP_YellowSign_WaveCustom_C>();
	}
};
DUMPER7_ASSERTS_ALCBP_YellowSign_WaveCustom_C;

}

