#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LCBP_WeaponCustomSampleBox

#include "Basic.hpp"

#include "LCBP_WeaponCustomSampleBox_classes.hpp"
#include "LCBP_WeaponCustomSampleBox_parameters.hpp"


namespace SDK
{

// Function LCBP_WeaponCustomSampleBox.LCBP_WeaponCustomSampleBox_C.RemoveWeapon
// (Public, BlueprintCallable, BlueprintEvent)

void ALCBP_WeaponCustomSampleBox_C::RemoveWeapon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WeaponCustomSampleBox_C", "RemoveWeapon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_WeaponCustomSampleBox.LCBP_WeaponCustomSampleBox_C.ResetWeaponPoint
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALCBP_WeaponCustomSampleBox_C::ResetWeaponPoint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WeaponCustomSampleBox_C", "ResetWeaponPoint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_WeaponCustomSampleBox.LCBP_WeaponCustomSampleBox_C.SetCameraActivation
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsActive                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALCBP_WeaponCustomSampleBox_C::SetCameraActivation(bool IsActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WeaponCustomSampleBox_C", "SetCameraActivation");

	Params::LCBP_WeaponCustomSampleBox_C_SetCameraActivation Parms{};

	Parms.IsActive = IsActive;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LCBP_WeaponCustomSampleBox.LCBP_WeaponCustomSampleBox_C.SetWeapon
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             WeaponRowName                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALCBP_WeaponCustomSampleBox_C::SetWeapon(class FName WeaponRowName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WeaponCustomSampleBox_C", "SetWeapon");

	Params::LCBP_WeaponCustomSampleBox_C_SetWeapon Parms{};

	Parms.WeaponRowName = WeaponRowName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LCBP_WeaponCustomSampleBox.LCBP_WeaponCustomSampleBox_C.WeaponControl_Location
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   AddLocation                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALCBP_WeaponCustomSampleBox_C::WeaponControl_Location(const struct FVector& AddLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WeaponCustomSampleBox_C", "WeaponControl_Location");

	Params::LCBP_WeaponCustomSampleBox_C_WeaponControl_Location Parms{};

	Parms.AddLocation = std::move(AddLocation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LCBP_WeaponCustomSampleBox.LCBP_WeaponCustomSampleBox_C.WeaponControl_Rotation
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FRotator&                  AddRotation                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ALCBP_WeaponCustomSampleBox_C::WeaponControl_Rotation(const struct FRotator& AddRotation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_WeaponCustomSampleBox_C", "WeaponControl_Rotation");

	Params::LCBP_WeaponCustomSampleBox_C_WeaponControl_Rotation Parms{};

	Parms.AddRotation = std::move(AddRotation);

	UObject::ProcessEvent(Func, &Parms);
}

}

