#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LCBP_SkillUpgradeSlotNew

#include "Basic.hpp"

#include "LCBP_SkillUpgradeSlotNew_classes.hpp"
#include "LCBP_SkillUpgradeSlotNew_parameters.hpp"


namespace SDK
{

// Function LCBP_SkillUpgradeSlotNew.LCBP_SkillUpgradeSlotNew_C.ExecuteUbergraph_LCBP_SkillUpgradeSlotNew
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALCBP_SkillUpgradeSlotNew_C::ExecuteUbergraph_LCBP_SkillUpgradeSlotNew(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_SkillUpgradeSlotNew_C", "ExecuteUbergraph_LCBP_SkillUpgradeSlotNew");

	Params::LCBP_SkillUpgradeSlotNew_C_ExecuteUbergraph_LCBP_SkillUpgradeSlotNew Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LCBP_SkillUpgradeSlotNew.LCBP_SkillUpgradeSlotNew_C.Interact
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   SelectIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALCBP_SkillUpgradeSlotNew_C::Interact(class AActor* Actor, int32 SelectIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_SkillUpgradeSlotNew_C", "Interact");

	Params::LCBP_SkillUpgradeSlotNew_C_Interact Parms{};

	Parms.Actor = Actor;
	Parms.SelectIndex = SelectIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LCBP_SkillUpgradeSlotNew.LCBP_SkillUpgradeSlotNew_C.InteractInOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void ALCBP_SkillUpgradeSlotNew_C::InteractInOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_SkillUpgradeSlotNew_C", "InteractInOverlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_SkillUpgradeSlotNew.LCBP_SkillUpgradeSlotNew_C.InteractOutOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void ALCBP_SkillUpgradeSlotNew_C::InteractOutOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_SkillUpgradeSlotNew_C", "InteractOutOverlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LCBP_SkillUpgradeSlotNew.LCBP_SkillUpgradeSlotNew_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ALCBP_SkillUpgradeSlotNew_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LCBP_SkillUpgradeSlotNew_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

