#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MTask_MoveToCover

#include "Basic.hpp"

#include "ALS_Gait_structs.hpp"
#include "MTask_Base_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass MTask_MoveToCover.MTask_MoveToCover_C
// 0x0018 (0x0048 - 0x0030)
class UMTask_MoveToCover_C final : public UMTask_Base_C
{
public:
	EALS_Gait                                     MoveSpeed;                                         // 0x0029(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CoverLocation;                                     // 0x0030(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void GetTaskInfo(EALS_Gait* MoveSpeed_0, struct FVector* CoverLocation_0);
	void SetTaskInfo(EALS_Gait MoveSpeed_0, const struct FVector& CoverLocation_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MTask_MoveToCover_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MTask_MoveToCover_C")
	}
	static class UMTask_MoveToCover_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMTask_MoveToCover_C>();
	}
};
DUMPER7_ASSERTS_UMTask_MoveToCover_C;

}

