#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MTask_MoveToRandom

#include "Basic.hpp"

#include "MTask_MoveToRandom_classes.hpp"
#include "MTask_MoveToRandom_parameters.hpp"


namespace SDK
{

// Function MTask_MoveToRandom.MTask_MoveToRandom_C.GetTaskInfo
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EALS_Gait*                              MoveSpeed_0                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         CoverLocation_0                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMTask_MoveToRandom_C::GetTaskInfo(EALS_Gait* MoveSpeed_0, struct FVector* CoverLocation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MTask_MoveToRandom_C", "GetTaskInfo");

	Params::MTask_MoveToRandom_C_GetTaskInfo Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (MoveSpeed_0 != nullptr)
		*MoveSpeed_0 = Parms.MoveSpeed_0;

	if (CoverLocation_0 != nullptr)
		*CoverLocation_0 = std::move(Parms.CoverLocation_0);
}


// Function MTask_MoveToRandom.MTask_MoveToRandom_C.SetTaskInfo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EALS_Gait                               MoveSpeed_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   CoverLocation_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMTask_MoveToRandom_C::SetTaskInfo(EALS_Gait MoveSpeed_0, const struct FVector& CoverLocation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MTask_MoveToRandom_C", "SetTaskInfo");

	Params::MTask_MoveToRandom_C_SetTaskInfo Parms{};

	Parms.MoveSpeed_0 = MoveSpeed_0;
	Parms.CoverLocation_0 = std::move(CoverLocation_0);

	UObject::ProcessEvent(Func, &Parms);
}

}

