#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Str_TaskReward

#include "Basic.hpp"

#include "EN_TaskRewardCategory_structs.hpp"


namespace SDK
{

// UserDefinedStruct Str_TaskReward.Str_TaskReward
// 0x0010 (0x0010 - 0x0000)
struct FStr_TaskReward final
{
public:
	EN_TaskRewardCategory                         Category_8_3A957A0C4C655E0B3A6CA6B762C178D4;       // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Amount_4_6CE3F3D14F98FB6A5F3C148B26914534;         // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   UnlockRowName_7_A000CD414BACACC2A44AF7A4CC0B613C;  // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FStr_TaskReward;

}

