#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Str_PartsAndPath

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Str_PartsAndPath.Str_PartsAndPath
// 0x0018 (0x0018 - 0x0000)
struct FStr_PartsAndPath final
{
public:
	class FName                                   PartsRowName_8_31109DA14310F146AC4A19B98F6E179C;   // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<uint8>                                 WeaponLocalPath_7_09DDD073471D5C492166FCA968C02EC4; // 0x0008(0x0010)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_FStr_PartsAndPath;

}

