#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Str_DiscType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Str_DiscType.Str_DiscType
// 0x0038 (0x0038 - 0x0000)
struct FStr_DiscType final
{
public:
	class FText                                   Name_4_6D66D09B42A450784E0DA9A439A33E6D;           // 0x0000(0x0010)(Edit, BlueprintVisible)
	TSoftObjectPtr<class UStaticMesh>             Mesh_7_A5FA6E854F2074B8C963ED8335440D82;           // 0x0010(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FStr_DiscType;

}

