#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Str_KickAnimValue

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Str_KickAnimValue.Str_KickAnimValue
// 0x0028 (0x0028 - 0x0000)
struct FStr_KickAnimValue final
{
public:
	double                                        BlendAlpha_2_091FE1CC47FB72ADB5CC40AC701620B9;     // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Thigh_L_5_D7B8AA4644665650AE7BF4AE4A7DACAE;        // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Calf_L_7_2F138E164DD2DBED9EEE3688E41823E5;         // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Foot_L_9_9B135D754E45DB004ED5429488B6CB87;         // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Ball_L_11_F784155647D42BEAC1B4F38B923C4E29;        // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FStr_KickAnimValue;

}

