#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Str_AiFirePattern

#include "Basic.hpp"

#include "EN_GunFirePattern_structs.hpp"


namespace SDK
{

// UserDefinedStruct Str_AiFirePattern.Str_AiFirePattern
// 0x0006 (0x0006 - 0x0000)
struct FStr_AiFirePattern final
{
public:
	EN_GunFirePattern                             Semi_Close_15_C24D2CC243DEAA1967920C8CB9EEE82C;    // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EN_GunFirePattern                             Semi_Middle_16_79F85ECD45E33D913CD24C8451E40EDB;   // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EN_GunFirePattern                             Semi_Far_17_ED2D5DF24E2D8617E7830393036C0D45;      // 0x0002(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EN_GunFirePattern                             Full_Close_24_C72DB7F84BC6C55E58A10B8C38D018E3;    // 0x0003(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EN_GunFirePattern                             Full_Middle_25_8A2E10924CD10C13D13495AC9E180AAA;   // 0x0004(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EN_GunFirePattern                             Full_Far_26_19C6C60E4AE58585CC6DB3A0CD14A5F1;      // 0x0005(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FStr_AiFirePattern;

}

