#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Str_CurrentAmmo

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Str_CurrentAmmo.Str_CurrentAmmo
// 0x0008 (0x0008 - 0x0000)
struct FStr_CurrentAmmo final
{
public:
	int32                                         Chamber_2_5E4763BD4614DEAF5DDA6BA133ABB63D;        // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Magazine_4_D0821B044BEF724C6EA1FCB38270C490;       // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FStr_CurrentAmmo;

}

