#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Str_LevelData

#include "Basic.hpp"

#include "Str_SpawnListData_structs.hpp"
#include "EN_SpawnCombatType_structs.hpp"
#include "EN_Faction_structs.hpp"


namespace SDK
{

// UserDefinedStruct Str_LevelData.Str_LevelData
// 0x0148 (0x0148 - 0x0000)
struct FStr_LevelData final
{
public:
	class FText                                   AreaName_68_6EFAF7F849594727327930837B03FAC4;      // 0x0000(0x0010)(Edit, BlueprintVisible)
	uint8                                         Hole_Amount_28_9152C5D043928F46B7D813A57222986D;   // 0x0010(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class USoundAttenuation>       Hole_OffLoopAttanuation_124_5A09415A4133A97AD6EB3E8C3BF3AD10; // 0x0018(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<struct FStr_SpawnListData>             NPC_SpawnList_105_9297D6C64472A0D2FF94C28495AA4AE5; // 0x0040(0x0010)(Edit, BlueprintVisible)
	TMap<EN_Faction, uint8>                       NPC_Amount_LimitByFaction_116_E21BF4184EBF1F6D168C4B996FE8AC11; // 0x0050(0x0050)(Edit, BlueprintVisible)
	uint8                                         NPC_Amount_StartLimit_108_27D78D08456E2D773AB6C1BBC668E0F1; // 0x00A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         NPC_Amount_EndLimit_110_CEB23B364222A260F5C29387C931DEB7; // 0x00A1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         NPC_OneSpawnMax_30_8DDA34B8421DF92554D719B471171A4F; // 0x00A2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EN_SpawnCombatType                            NPC_CombatType_31_933DE56F42A9C26BF2B3DDB00C1BD36E; // 0x00A3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        NPC_Interval_Base_33_E357CA3B4BFEDA86174C2A9D172B4198; // 0x00A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        NPC_Interval_RandomRange_34_20E3A51841039D881A0830914467CFCE; // 0x00B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        NPC_DropCashDataMultiplier_111_A65514E3476C612EE83732BB6966F05F; // 0x00B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         ItemBox_SpawnAmount_Max_97_8F6FED1F4824A44A6A8F16A7FB02F50F; // 0x00C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         ItemBox_SpawnAmount_Min_96_3D81ED9C49C7592FE0191395FE03EBC5; // 0x00C1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C2[0x6];                                       // 0x00C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<TSoftClassPtr<class UClass>, double>     ItemBox_SpawnRate_95_84695B4142C9688504F6498D7E93BE0E; // 0x00C8(0x0050)(Edit, BlueprintVisible)
	class FName                                   Fridge_SpawnFridgeRowName_120_ED85DE7A41094593E8558B81E5897511; // 0x0118(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UTexture2D>              AreaImage_64_408612244482244A930BACB578D860BA;     // 0x0120(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FStr_LevelData;

}

