#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Str_MeleePartsData

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Str_MeleePartsData.Str_MeleePartsData
// 0x0038 (0x0038 - 0x0000)
struct FStr_MeleePartsData final
{
public:
	class FText                                   PartsName_2_A5A4D3D24DE826ED9F961E8C07024F39;      // 0x0000(0x0010)(Edit, BlueprintVisible)
	TSoftClassPtr<class UClass>                   BP_6_1F39433E495580549879048CC26F31FD;             // 0x0010(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FStr_MeleePartsData;

}

