#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIM_Title

#include "Basic.hpp"

#include "UIM_Title_classes.hpp"
#include "UIM_Title_parameters.hpp"


namespace SDK
{

// Function UIM_Title.UIM_Title_C.BndEvt__UIM_Title_UIM_YesNo_K2Node_ComponentBoundEvent_5_OnSelected__DelegateSignature
// (BlueprintEvent)
// Parameters:
// uint8                                   OpenNumber                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsYES                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIM_Title_C::BndEvt__UIM_Title_UIM_YesNo_K2Node_ComponentBoundEvent_5_OnSelected__DelegateSignature(uint8 OpenNumber, bool IsYES)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "BndEvt__UIM_Title_UIM_YesNo_K2Node_ComponentBoundEvent_5_OnSelected__DelegateSignature");

	Params::UIM_Title_C_BndEvt__UIM_Title_UIM_YesNo_K2Node_ComponentBoundEvent_5_OnSelected__DelegateSignature Parms{};

	Parms.OpenNumber = OpenNumber;
	Parms.IsYES = IsYES;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIM_Title.UIM_Title_C.BndEvt__UIM_Title_UIP_Btn_CREDIT_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_Title_C::BndEvt__UIM_Title_UIP_Btn_CREDIT_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "BndEvt__UIM_Title_UIP_Btn_CREDIT_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_Title.UIM_Title_C.BndEvt__UIM_Title_UIP_Button_Secondary_1_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_Title_C::BndEvt__UIM_Title_UIP_Button_Secondary_1_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "BndEvt__UIM_Title_UIP_Button_Secondary_1_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_Title.UIM_Title_C.BndEvt__UIM_Title_UIP_Button_Secondary_2_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_Title_C::BndEvt__UIM_Title_UIP_Button_Secondary_2_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "BndEvt__UIM_Title_UIP_Button_Secondary_2_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_Title.UIM_Title_C.BndEvt__UIM_Title_UIP_Button_Secondary_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_Title_C::BndEvt__UIM_Title_UIP_Button_Secondary_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "BndEvt__UIM_Title_UIP_Button_Secondary_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_Title.UIM_Title_C.BndEvt__UIM_Title_UIP_FocusLostCover_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_Title_C::BndEvt__UIM_Title_UIP_FocusLostCover_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "BndEvt__UIM_Title_UIP_FocusLostCover_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_Title.UIM_Title_C.CloseWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIM_Title_C::CloseWidget(bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "CloseWidget");

	Params::UIM_Title_C_CloseWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Success != nullptr)
		*Success = Parms.Success;
}


// Function UIM_Title.UIM_Title_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIM_Title_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_Title.UIM_Title_C.ExecuteUbergraph_UIM_Title
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIM_Title_C::ExecuteUbergraph_UIM_Title(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "ExecuteUbergraph_UIM_Title");

	Params::UIM_Title_C_ExecuteUbergraph_UIM_Title Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIM_Title.UIM_Title_C.FocusLoopDown
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIM_Title_C::FocusLoopDown(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "FocusLoopDown");

	Params::UIM_Title_C_FocusLoopDown Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIM_Title.UIM_Title_C.FocusLoopUp
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIM_Title_C::FocusLoopUp(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "FocusLoopUp");

	Params::UIM_Title_C_FocusLoopUp Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIM_Title.UIM_Title_C.GetFocusWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EN_WidgetFocusDirection                 MoveInDirection                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget**                         FocusTargetWidget                                      (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUIM_Title_C::GetFocusWidget(EN_WidgetFocusDirection MoveInDirection, class UWidget** FocusTargetWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "GetFocusWidget");

	Params::UIM_Title_C_GetFocusWidget Parms{};

	Parms.MoveInDirection = MoveInDirection;

	UObject::ProcessEvent(Func, &Parms);

	if (FocusTargetWidget != nullptr)
		*FocusTargetWidget = Parms.FocusTargetWidget;
}


// Function UIM_Title.UIM_Title_C.InitializeFocus
// (Public, BlueprintCallable, BlueprintEvent)

void UUIM_Title_C::InitializeFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "InitializeFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_Title.UIM_Title_C.IsOpened
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsOpen                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIM_Title_C::IsOpened(bool* IsOpen)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "IsOpened");

	Params::UIM_Title_C_IsOpened Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsOpen != nullptr)
		*IsOpen = Parms.IsOpen;
}


// Function UIM_Title.UIM_Title_C.SetPreWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          PreWidget                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUIM_Title_C::SetPreWidget(class UWidget* PreWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_Title_C", "SetPreWidget");

	Params::UIM_Title_C_SetPreWidget Parms{};

	Parms.PreWidget = PreWidget;

	UObject::ProcessEvent(Func, &Parms);
}

}

