#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIM_Task

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Str_TaskCardState_structs.hpp"
#include "SlateCore_structs.hpp"
#include "Str_PopupData_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"
#include "EN_WidgetFocusDirection_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UIM_Task.UIM_Task_C
// 0x00C8 (0x0398 - 0x02D0)
class UUIM_Task_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       ShowCards;                                         // 0x02D8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UTextBlock*                             Text_NoTask;                                       // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIP_Button_Secondary_C*                UIP_Btn_Return;                                    // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIP_Button_Primary_C*                  UIP_Btn_Reward_1;                                  // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIP_Button_Primary_C*                  UIP_Btn_Reward_2;                                  // 0x02F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIP_Button_Primary_C*                  UIP_Btn_Reward_3;                                  // 0x0300(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIP_FocusLostCover_C*                  UIP_FocusLostCover;                                // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIS_TaskCard_C*                        UIS_TaskCard_1;                                    // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIS_TaskCard_C*                        UIS_TaskCard_2;                                    // 0x0318(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIS_TaskCard_C*                        UIS_TaskCard_3;                                    // 0x0320(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMap<uint8, struct FStr_TaskCardState>        Task;                                              // 0x0328(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          IsHome;                                            // 0x0378(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IsOpen;                                            // 0x0379(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsDebugMode;                                       // 0x037A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37B[0x5];                                      // 0x037B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                Pre_Widget;                                        // 0x0380(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<struct FStr_PopupData>                 RewardData;                                        // 0x0388(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void AddNewTask(uint8 Slot_0);
	void BndEvt__UIM_Quest_UIP_Btn_Return_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature();
	void BndEvt__UIM_Quest_UIP_Btn_Reward_1_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature();
	void BndEvt__UIM_Quest_UIP_Btn_Reward_2_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature();
	void BndEvt__UIM_Quest_UIP_Btn_Reward_3_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature();
	void BndEvt__UIM_Quest_UIP_FocusLostCover_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
	void ChangeTask(uint8 Slot_0);
	void CloseWidget(bool* Success);
	void Construct();
	void CustomEvent();
	void ExecuteUbergraph_UIM_Task(int32 EntryPoint);
	class UWidget* FocusMove_CardsToReturn(EUINavigation Navigation_0);
	class UWidget* FocusMove_PushCardsButton(EUINavigation Navigation_0, class UWidget* Widget);
	class UWidget* FocusMove_ReturnToCards(EUINavigation Navigation_0);
	void GetFocusWidget(EN_WidgetFocusDirection MoveInDirection, class UWidget** FocusTargetWidget);
	void InitializeFocus();
	void IsOpened(bool* IsOpen_0);
	void PlayOpenCardSound(class UOverlay* Card);
	void PushRewardButton(uint8 Slot_0, class UUIS_TaskCard_C* UIS_TaskCard, class UWidget* UIP_RewardButton);
	void RefreshTaskData();
	void SequenceEvent__ENTRYPOINTUIM_Task(class UOverlay* TaskCard_1);
	void SequenceEvent__ENTRYPOINTUIM_Task_0(class UOverlay* TaskCard_2);
	void SequenceEvent__ENTRYPOINTUIM_Task_1(class UOverlay* TaskCard_3);
	void SetPreWidget(class UWidget* PreWidget);
	void SwitchRewardButton(class UUIP_Button_Primary_C* Button, class UUIS_TaskCard_C* Card, const struct FStr_TaskCardState& TaskCardState);
	void TaskCard_1_Event(class UOverlay* TaskCard_1);
	void TaskCard_2_Event(class UOverlay* TaskCard_2);
	void TaskCard_3_Event(class UOverlay* TaskCard_3);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UIM_Task_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UIM_Task_C")
	}
	static class UUIM_Task_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIM_Task_C>();
	}
};
DUMPER7_ASSERTS_UUIM_Task_C;

}

