#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIM_HUD

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "EN_TaskUI_structs.hpp"
#include "EN_HUDMode_structs.hpp"
#include "EN_TaskUIViewMode_structs.hpp"
#include "EN_SaveState_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"
#include "EN_IconMode_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UIM_HUD.UIM_HUD_C
// 0x0088 (0x0358 - 0x02D0)
class UUIM_HUD_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHUDP_Ammo_C*                           HUDP_Ammo;                                         // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUDP_BarrelHeat_C*                     HUDP_BarrelHeat;                                   // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUDP_CashData_C*                       HUDP_CashData;                                     // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUDP_Crosshair_C*                      HUDP_Crosshair;                                    // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUDP_DebugHP_B_C*                      HUDP_DebugHP;                                      // 0x02F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUDP_Fridge_C*                         HUDP_Fridge;                                       // 0x0300(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUDP_Interact_C*                       HUDP_Interact;                                     // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUDP_Light_C*                          HUDP_Light;                                        // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUDP_NavIcon_C*                        HUDP_NavIcon;                                      // 0x0318(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUDP_OBJ_C*                            HUDP_OBJ;                                          // 0x0320(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUDP_Popup_C*                          HUDP_Popup;                                        // 0x0328(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUDP_ReloadHint_C*                     HUDP_ReloadHint;                                   // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHUDP_SaveProgress_C*                   HUDP_SaveProgress;                                 // 0x0338(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          EnableCrosshair;                                   // 0x0340(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EN_TaskUIViewMode                             TaskUIViewMode;                                    // 0x0341(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EN_TaskUI                                     TempTask;                                          // 0x0342(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EN_TaskUI                                     Delay_Anim_Task;                                   // 0x0343(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DelayAnim_IsOpen;                                  // 0x0344(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_345[0x3];                                      // 0x0345(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           Timer;                                             // 0x0348(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          TempIsOpen;                                        // 0x0350(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsGamepadIconMode;                                 // 0x0351(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Animation_0();
	void Construct();
	void ControlCrosshair(bool EnableCrosshair_0);
	void ControlOBJMovie(double RenderOpacity_0, class UMediaSource* MediaSource);
	void DelayAnimation(EN_TaskUI DelayAnim_Task, bool DelayAnim_IsOpen_0, double DelayTime);
	void ExecuteUbergraph_UIM_HUD(int32 EntryPoint);
	void GetInteractUI_SelectNum(int32* SelectNum);
	void GetInteractUI_TextLength(int32* Length);
	void GetInteractUI_Visible(bool* IsVisible_0);
	void HideCashData();
	void HideFridgeProgress();
	void HideInteractUI(bool IsAnimation);
	void ImportConfigData(bool EnableCrosshair_0, EN_TaskUIViewMode TaskIcon, EN_HUDMode HUDMode);
	void InpActEvt_AnyKey_K2Node_InputKeyEvent_0(const struct FKey& Key);
	void MoveSelectorInteractUI(bool IsUp);
	void NavUI_Control(bool IsOpen, EN_TaskUI Task, bool IsPlayerInput);
	void NavUI_Initialize();
	void NavUI_PlayAnim(EN_TaskUI Task, bool IsOpenAnim);
	void RefreshCashData(int32 Cash, int32 Data);
	void SetFireMode(EN_IconMode Safety, EN_IconMode SemiAuto, EN_IconMode FullAuto);
	void SetFridgeProgress(double Progress, int32 WaveCount);
	void SetHoleProgress(double Percent);
	void SetHUDHP(double HP, double MaxHP);
	void SetLightMode(EN_IconMode LightMode);
	void SetReloadHint(int32 ChamberAmmoNum, int32 MagAmmoNum, bool IsMelee, bool IsJamming, bool IsBoltAction, bool IsBoltOpen);
	void SetTargetKillCount(int32 TargetKillCount);
	void ShowCashData();
	void ShowFridgeProgress();
	void ShowInteractUI(TArray<struct FStr_InteractUIText>& Text);
	void ShowPopup(class UTexture2D* Icon, const class FText& Text, bool IsStack, class FName StackID, int32 Stack_Amount, bool IsFitIcon);
	void UpdateAmmo(int32 AmmoInChamber, int32 AmmoInMagazine);
	void UpdateBarrelHeat(double BarrelHeat, double Normalized);
	void UpdateSaveProgress(EN_SaveState SaveState);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UIM_HUD_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UIM_HUD_C")
	}
	static class UUIM_HUD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIM_HUD_C>();
	}
};
DUMPER7_ASSERTS_UUIM_HUD_C;

}

