#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIM_WeaponCustom

#include "Basic.hpp"

#include "UIM_WeaponCustom_classes.hpp"
#include "UIM_WeaponCustom_parameters.hpp"


namespace SDK
{

// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_BTN_Close_K2Node_ComponentBoundEvent_27_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_BTN_Close_K2Node_ComponentBoundEvent_27_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_BTN_Close_K2Node_ComponentBoundEvent_27_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_AR_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_AR_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_AR_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_HG_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_HG_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_HG_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_00_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_00_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_00_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_00_K2Node_ComponentBoundEvent_17_OnHovered__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_00_K2Node_ComponentBoundEvent_17_OnHovered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_00_K2Node_ComponentBoundEvent_17_OnHovered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_00_K2Node_ComponentBoundEvent_22_OnUnhovered__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_00_K2Node_ComponentBoundEvent_22_OnUnhovered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_00_K2Node_ComponentBoundEvent_22_OnUnhovered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_01_K2Node_ComponentBoundEvent_12_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_01_K2Node_ComponentBoundEvent_12_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_01_K2Node_ComponentBoundEvent_12_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_01_K2Node_ComponentBoundEvent_18_OnHovered__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_01_K2Node_ComponentBoundEvent_18_OnHovered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_01_K2Node_ComponentBoundEvent_18_OnHovered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_01_K2Node_ComponentBoundEvent_23_OnUnhovered__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_01_K2Node_ComponentBoundEvent_23_OnUnhovered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_01_K2Node_ComponentBoundEvent_23_OnUnhovered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_02_K2Node_ComponentBoundEvent_13_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_02_K2Node_ComponentBoundEvent_13_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_02_K2Node_ComponentBoundEvent_13_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_02_K2Node_ComponentBoundEvent_19_OnHovered__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_02_K2Node_ComponentBoundEvent_19_OnHovered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_02_K2Node_ComponentBoundEvent_19_OnHovered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_02_K2Node_ComponentBoundEvent_24_OnUnhovered__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_02_K2Node_ComponentBoundEvent_24_OnUnhovered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_02_K2Node_ComponentBoundEvent_24_OnUnhovered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_03_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_03_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_03_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_03_K2Node_ComponentBoundEvent_20_OnHovered__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_03_K2Node_ComponentBoundEvent_20_OnHovered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_03_K2Node_ComponentBoundEvent_20_OnHovered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_03_K2Node_ComponentBoundEvent_25_OnUnhovered__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_03_K2Node_ComponentBoundEvent_25_OnUnhovered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_03_K2Node_ComponentBoundEvent_25_OnUnhovered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_04_K2Node_ComponentBoundEvent_15_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_04_K2Node_ComponentBoundEvent_15_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_04_K2Node_ComponentBoundEvent_15_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_04_K2Node_ComponentBoundEvent_21_OnHovered__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_04_K2Node_ComponentBoundEvent_21_OnHovered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_04_K2Node_ComponentBoundEvent_21_OnHovered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_04_K2Node_ComponentBoundEvent_26_OnUnhovered__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_04_K2Node_ComponentBoundEvent_26_OnUnhovered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Parts_04_K2Node_ComponentBoundEvent_26_OnUnhovered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_SG_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_SG_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_SG_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_01_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_01_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_01_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_02_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_02_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_02_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_03_K2Node_ComponentBoundEvent_6_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_03_K2Node_ComponentBoundEvent_6_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_03_K2Node_ComponentBoundEvent_6_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_04_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_04_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_04_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_05_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_05_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_05_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_06_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_06_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_06_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_07_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_07_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_07_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_08_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_08_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_Slot_08_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_BSI_SR_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_BSI_SR_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_BSI_SR_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_FocusLostCover_K2Node_ComponentBoundEvent_28_OnClicked__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_FocusLostCover_K2Node_ComponentBoundEvent_28_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_FocusLostCover_K2Node_ComponentBoundEvent_28_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.BndEvt__UIM_WeaponCustom_UIP_WeaponModelControllPanel_K2Node_ComponentBoundEvent_30_MouseButtonUp__DelegateSignature
// (BlueprintEvent)

void UUIM_WeaponCustom_C::BndEvt__UIM_WeaponCustom_UIP_WeaponModelControllPanel_K2Node_ComponentBoundEvent_30_MouseButtonUp__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "BndEvt__UIM_WeaponCustom_UIP_WeaponModelControllPanel_K2Node_ComponentBoundEvent_30_MouseButtonUp__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.CloseParts
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsAnim                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIM_WeaponCustom_C::CloseParts(bool IsAnim)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "CloseParts");

	Params::UIM_WeaponCustom_C_CloseParts Parms{};

	Parms.IsAnim = IsAnim;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.CloseSlots
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsAnim                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIM_WeaponCustom_C::CloseSlots(bool IsAnim)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "CloseSlots");

	Params::UIM_WeaponCustom_C_CloseSlots Parms{};

	Parms.IsAnim = IsAnim;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.CloseWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIM_WeaponCustom_C::CloseWidget(bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "CloseWidget");

	Params::UIM_WeaponCustom_C_CloseWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Success != nullptr)
		*Success = Parms.Success;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIM_WeaponCustom_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.CreateNewWeaponCustomSaveData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FStr_PartsAndPath>&       TempData                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<struct FStr_PartsAndPath>*       NewData                                                (Parm, OutParm)

void UUIM_WeaponCustom_C::CreateNewWeaponCustomSaveData(TArray<struct FStr_PartsAndPath>& TempData, TArray<struct FStr_PartsAndPath>* NewData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "CreateNewWeaponCustomSaveData");

	Params::UIM_WeaponCustom_C_CreateNewWeaponCustomSaveData Parms{};

	Parms.TempData = std::move(TempData);

	UObject::ProcessEvent(Func, &Parms);

	TempData = std::move(Parms.TempData);

	if (NewData != nullptr)
		*NewData = std::move(Parms.NewData);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.ExecuteUbergraph_UIM_WeaponCustom
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIM_WeaponCustom_C::ExecuteUbergraph_UIM_WeaponCustom(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "ExecuteUbergraph_UIM_WeaponCustom");

	Params::UIM_WeaponCustom_C_ExecuteUbergraph_UIM_WeaponCustom Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.FocusMove_CloseToParts
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIM_WeaponCustom_C::FocusMove_CloseToParts(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "FocusMove_CloseToParts");

	Params::UIM_WeaponCustom_C_FocusMove_CloseToParts Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.FocusMove_CloseToWeapon
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIM_WeaponCustom_C::FocusMove_CloseToWeapon(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "FocusMove_CloseToWeapon");

	Params::UIM_WeaponCustom_C_FocusMove_CloseToWeapon Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.FocusMove_PartsToSlot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIM_WeaponCustom_C::FocusMove_PartsToSlot(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "FocusMove_PartsToSlot");

	Params::UIM_WeaponCustom_C_FocusMove_PartsToSlot Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.FocusMove_SlotToParts
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIM_WeaponCustom_C::FocusMove_SlotToParts(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "FocusMove_SlotToParts");

	Params::UIM_WeaponCustom_C_FocusMove_SlotToParts Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.FocusMove_SlotToWeapon
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIM_WeaponCustom_C::FocusMove_SlotToWeapon(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "FocusMove_SlotToWeapon");

	Params::UIM_WeaponCustom_C_FocusMove_SlotToWeapon Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.FocusMove_ToClose
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIM_WeaponCustom_C::FocusMove_ToClose(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "FocusMove_ToClose");

	Params::UIM_WeaponCustom_C_FocusMove_ToClose Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.FocusMove_WeaponToSlot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIM_WeaponCustom_C::FocusMove_WeaponToSlot(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "FocusMove_WeaponToSlot");

	Params::UIM_WeaponCustom_C_FocusMove_WeaponToSlot Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.GetCustomizedSpec
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             WeaponRowName                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FStr_GunSpecData*                CustomizedSpec                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Succsess                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIM_WeaponCustom_C::GetCustomizedSpec(class FName WeaponRowName, struct FStr_GunSpecData* CustomizedSpec, bool* Succsess)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "GetCustomizedSpec");

	Params::UIM_WeaponCustom_C_GetCustomizedSpec Parms{};

	Parms.WeaponRowName = WeaponRowName;

	UObject::ProcessEvent(Func, &Parms);

	if (CustomizedSpec != nullptr)
		*CustomizedSpec = std::move(Parms.CustomizedSpec);

	if (Succsess != nullptr)
		*Succsess = Parms.Succsess;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.GetDeltaSpec
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             WeaponRowName                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             NewPartsRowName                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   TargetIndexPath                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FStr_GunSpecData*                DeltaSpec                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FStr_GunSpecData*                NewCustomizedSpec                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIM_WeaponCustom_C::GetDeltaSpec(class FName WeaponRowName, class FName NewPartsRowName, uint8 TargetIndexPath, struct FStr_GunSpecData* DeltaSpec, struct FStr_GunSpecData* NewCustomizedSpec, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "GetDeltaSpec");

	Params::UIM_WeaponCustom_C_GetDeltaSpec Parms{};

	Parms.WeaponRowName = WeaponRowName;
	Parms.NewPartsRowName = NewPartsRowName;
	Parms.TargetIndexPath = TargetIndexPath;

	UObject::ProcessEvent(Func, &Parms);

	if (DeltaSpec != nullptr)
		*DeltaSpec = std::move(Parms.DeltaSpec);

	if (NewCustomizedSpec != nullptr)
		*NewCustomizedSpec = std::move(Parms.NewCustomizedSpec);

	if (Success != nullptr)
		*Success = Parms.Success;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.GetFocusWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EN_WidgetFocusDirection                 MoveInDirection                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget**                         FocusTargetWidget                                      (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUIM_WeaponCustom_C::GetFocusWidget(EN_WidgetFocusDirection MoveInDirection, class UWidget** FocusTargetWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "GetFocusWidget");

	Params::UIM_WeaponCustom_C_GetFocusWidget Parms{};

	Parms.MoveInDirection = MoveInDirection;

	UObject::ProcessEvent(Func, &Parms);

	if (FocusTargetWidget != nullptr)
		*FocusTargetWidget = Parms.FocusTargetWidget;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.InitializeFocus
// (Public, BlueprintCallable, BlueprintEvent)

void UUIM_WeaponCustom_C::InitializeFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "InitializeFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.IsOpened
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsOpen_0                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIM_WeaponCustom_C::IsOpened(bool* IsOpen_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "IsOpened");

	Params::UIM_WeaponCustom_C_IsOpened Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsOpen_0 != nullptr)
		*IsOpen_0 = Parms.IsOpen_0;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.OnAnalogValueChanged
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FAnalogInputEvent&         InAnalogInputEvent                                     (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUIM_WeaponCustom_C::OnAnalogValueChanged(const struct FGeometry& MyGeometry, const struct FAnalogInputEvent& InAnalogInputEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "OnAnalogValueChanged");

	Params::UIM_WeaponCustom_C_OnAnalogValueChanged Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InAnalogInputEvent = std::move(InAnalogInputEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.OnKeyUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUIM_WeaponCustom_C::OnKeyUp(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "OnKeyUp");

	Params::UIM_WeaponCustom_C_OnKeyUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.OnMouseButtonUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUIM_WeaponCustom_C::OnMouseButtonUp(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "OnMouseButtonUp");

	Params::UIM_WeaponCustom_C_OnMouseButtonUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.OpenParts
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIP_Button_Switcher_Image_C*     Slot_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUIM_WeaponCustom_C::OpenParts(class UUIP_Button_Switcher_Image_C* Slot_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "OpenParts");

	Params::UIM_WeaponCustom_C_OpenParts Parms{};

	Parms.Slot_0 = Slot_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.OpenSlots
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SelectedWeaponRowName_0                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIM_WeaponCustom_C::OpenSlots(class FName SelectedWeaponRowName_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "OpenSlots");

	Params::UIM_WeaponCustom_C_OpenSlots Parms{};

	Parms.SelectedWeaponRowName_0 = SelectedWeaponRowName_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.SelectParts
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIP_Button_Switcher_Image_C*     Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUIM_WeaponCustom_C::SelectParts(class UUIP_Button_Switcher_Image_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "SelectParts");

	Params::UIM_WeaponCustom_C_SelectParts Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.SetPartsText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             PartsRowName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIM_WeaponCustom_C::SetPartsText(class FName PartsRowName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "SetPartsText");

	Params::UIM_WeaponCustom_C_SetPartsText Parms{};

	Parms.PartsRowName = PartsRowName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.SetPreWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          PreWidget                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUIM_WeaponCustom_C::SetPreWidget(class UWidget* PreWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "SetPreWidget");

	Params::UIM_WeaponCustom_C_SetPreWidget Parms{};

	Parms.PreWidget = PreWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIM_WeaponCustom.UIM_WeaponCustom_C.SetWeaponSpec
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             WeaponRowName                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             NewPartsRowName                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIM_WeaponCustom_C::SetWeaponSpec(class FName WeaponRowName, class FName NewPartsRowName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIM_WeaponCustom_C", "SetWeaponSpec");

	Params::UIM_WeaponCustom_C_SetWeaponSpec Parms{};

	Parms.WeaponRowName = WeaponRowName;
	Parms.NewPartsRowName = NewPartsRowName;

	UObject::ProcessEvent(Func, &Parms);
}

}

