#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIP_Option_CheckBox

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"
#include "EN_WidgetFocusDirection_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UIP_Option_CheckBox.UIP_Option_CheckBox_C
// 0x12F0 (0x15C0 - 0x02D0)
class UUIP_Option_CheckBox_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCheckBox*                              CheckBox;                                          // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock;                                         // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Text;                                              // 0x02E8(0x0010)(Edit, BlueprintVisible)
	int32                                         FontSize;                                          // 0x02F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2FC[0x4];                                      // 0x02FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCheckBoxStyle                         UnhoverStyle;                                      // 0x0300(0x0950)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FCheckBoxStyle                         HoverStyle;                                        // 0x0C50(0x0950)(Edit, BlueprintVisible, DisableEditOnInstance)
	ECheckBoxState                                CheckedState;                                      // 0x15A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15A1[0x7];                                     // 0x15A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              StateChanged;                                      // 0x15A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__UIP_Option_CheckBox_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
	void CloseWidget(bool* Success);
	void ExecuteUbergraph_UIP_Option_CheckBox(int32 EntryPoint);
	void GetFocusWidget(EN_WidgetFocusDirection MoveInDirection, class UWidget** FocusTargetWidget);
	void GetSelectedValue(bool* Value);
	void InitializeCheckBox();
	void InitializeFocus();
	void IsOpened(bool* IsOpen);
	void PreConstruct(bool IsDesignTime);
	void SetPreWidget(class UWidget* PreWidget);
	void SetSelectedValue(bool SelectedBool);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UIP_Option_CheckBox_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UIP_Option_CheckBox_C")
	}
	static class UUIP_Option_CheckBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIP_Option_CheckBox_C>();
	}
};
DUMPER7_ASSERTS_UUIP_Option_CheckBox_C;

}

