#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIP_Option_CheckBox

#include "Basic.hpp"

#include "EN_WidgetFocusDirection_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function UIP_Option_CheckBox.UIP_Option_CheckBox_C.BndEvt__UIP_Option_CheckBox_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct UIP_Option_CheckBox_C_BndEvt__UIP_Option_CheckBox_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature final
{
public:
	bool                                          bIsChecked;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UIP_Option_CheckBox_C_BndEvt__UIP_Option_CheckBox_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature;

// Function UIP_Option_CheckBox.UIP_Option_CheckBox_C.CloseWidget
// 0x0001 (0x0001 - 0x0000)
struct UIP_Option_CheckBox_C_CloseWidget final
{
public:
	bool                                          Success;                                           // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UIP_Option_CheckBox_C_CloseWidget;

// Function UIP_Option_CheckBox.UIP_Option_CheckBox_C.ExecuteUbergraph_UIP_Option_CheckBox
// 0x09C0 (0x09C0 - 0x0000)
struct UIP_Option_CheckBox_C_ExecuteUbergraph_UIP_Option_CheckBox final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                K2Node_Event_PreWidget;                            // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0014(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAnyUserFocus_ReturnValue;              // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_52[0xE];                                       // 0x0052(0x000E)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCheckBoxStyle                         K2Node_Select_Default;                             // 0x0060(0x0950)()
	bool                                          K2Node_ComponentBoundEvent_bIsChecked;             // 0x09B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UIP_Option_CheckBox_C_ExecuteUbergraph_UIP_Option_CheckBox;

// Function UIP_Option_CheckBox.UIP_Option_CheckBox_C.GetFocusWidget
// 0x0010 (0x0010 - 0x0000)
struct UIP_Option_CheckBox_C_GetFocusWidget final
{
public:
	EN_WidgetFocusDirection                       MoveInDirection;                                   // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                FocusTargetWidget;                                 // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UIP_Option_CheckBox_C_GetFocusWidget;

// Function UIP_Option_CheckBox.UIP_Option_CheckBox_C.GetSelectedValue
// 0x0007 (0x0007 - 0x0000)
struct UIP_Option_CheckBox_C_GetSelectedValue final
{
public:
	bool                                          Value;                                             // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECheckBoxState                                Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECheckBoxState                                CallFunc_GetCheckedState_ReturnValue;              // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Select_Default;                             // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UIP_Option_CheckBox_C_GetSelectedValue;

// Function UIP_Option_CheckBox.UIP_Option_CheckBox_C.InitializeCheckBox
// 0x09D0 (0x09D0 - 0x0000)
struct UIP_Option_CheckBox_C_InitializeCheckBox final
{
public:
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCheckBoxStyle                         K2Node_MakeStruct_CheckBoxStyle;                   // 0x0010(0x0950)()
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo;                   // 0x0960(0x0060)(HasGetValueTypeHash)
	float                                         K2Node_MakeStruct_Size_ImplicitCast;               // 0x09C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UIP_Option_CheckBox_C_InitializeCheckBox;

// Function UIP_Option_CheckBox.UIP_Option_CheckBox_C.IsOpened
// 0x0001 (0x0001 - 0x0000)
struct UIP_Option_CheckBox_C_IsOpened final
{
public:
	bool                                          IsOpen;                                            // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UIP_Option_CheckBox_C_IsOpened;

// Function UIP_Option_CheckBox.UIP_Option_CheckBox_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UIP_Option_CheckBox_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UIP_Option_CheckBox_C_PreConstruct;

// Function UIP_Option_CheckBox.UIP_Option_CheckBox_C.SetPreWidget
// 0x0008 (0x0008 - 0x0000)
struct UIP_Option_CheckBox_C_SetPreWidget final
{
public:
	class UWidget*                                PreWidget;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UIP_Option_CheckBox_C_SetPreWidget;

// Function UIP_Option_CheckBox.UIP_Option_CheckBox_C.SetSelectedValue
// 0x0005 (0x0005 - 0x0000)
struct UIP_Option_CheckBox_C_SetSelectedValue final
{
public:
	bool                                          SelectedBool;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECheckBoxState                                Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECheckBoxState                                Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECheckBoxState                                K2Node_Select_Default;                             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UIP_Option_CheckBox_C_SetSelectedValue;

// Function UIP_Option_CheckBox.UIP_Option_CheckBox_C.Tick
// 0x003C (0x003C - 0x0000)
struct UIP_Option_CheckBox_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UIP_Option_CheckBox_C_Tick;

}

