#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIS_OptionTab_Audio

#include "Basic.hpp"

#include "UIS_OptionTab_Audio_classes.hpp"
#include "UIS_OptionTab_Audio_parameters.hpp"


namespace SDK
{

// Function UIS_OptionTab_Audio.UIS_OptionTab_Audio_C.CloseWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIS_OptionTab_Audio_C::CloseWidget(bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIS_OptionTab_Audio_C", "CloseWidget");

	Params::UIS_OptionTab_Audio_C_CloseWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Success != nullptr)
		*Success = Parms.Success;
}


// Function UIS_OptionTab_Audio.UIS_OptionTab_Audio_C.ExecuteUbergraph_UIS_OptionTab_Audio
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIS_OptionTab_Audio_C::ExecuteUbergraph_UIS_OptionTab_Audio(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIS_OptionTab_Audio_C", "ExecuteUbergraph_UIS_OptionTab_Audio");

	Params::UIS_OptionTab_Audio_C_ExecuteUbergraph_UIS_OptionTab_Audio Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIS_OptionTab_Audio.UIS_OptionTab_Audio_C.FocusMoveDownOut
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIS_OptionTab_Audio_C::FocusMoveDownOut(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIS_OptionTab_Audio_C", "FocusMoveDownOut");

	Params::UIS_OptionTab_Audio_C_FocusMoveDownOut Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIS_OptionTab_Audio.UIS_OptionTab_Audio_C.FocusMoveUpOut
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUIS_OptionTab_Audio_C::FocusMoveUpOut(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIS_OptionTab_Audio_C", "FocusMoveUpOut");

	Params::UIS_OptionTab_Audio_C_FocusMoveUpOut Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIS_OptionTab_Audio.UIS_OptionTab_Audio_C.GetFocusWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EN_WidgetFocusDirection                 MoveInDirection                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget**                         FocusTargetWidget                                      (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUIS_OptionTab_Audio_C::GetFocusWidget(EN_WidgetFocusDirection MoveInDirection, class UWidget** FocusTargetWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIS_OptionTab_Audio_C", "GetFocusWidget");

	Params::UIS_OptionTab_Audio_C_GetFocusWidget Parms{};

	Parms.MoveInDirection = MoveInDirection;

	UObject::ProcessEvent(Func, &Parms);

	if (FocusTargetWidget != nullptr)
		*FocusTargetWidget = Parms.FocusTargetWidget;
}


// Function UIS_OptionTab_Audio.UIS_OptionTab_Audio_C.GetSelectedValues
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8*                                  Master                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8*                                  BGM                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8*                                  SE                                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8*                                  UI                                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIS_OptionTab_Audio_C::GetSelectedValues(uint8* Master, uint8* BGM, uint8* SE, uint8* UI)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIS_OptionTab_Audio_C", "GetSelectedValues");

	Params::UIS_OptionTab_Audio_C_GetSelectedValues Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Master != nullptr)
		*Master = Parms.Master;

	if (BGM != nullptr)
		*BGM = Parms.BGM;

	if (SE != nullptr)
		*SE = Parms.SE;

	if (UI != nullptr)
		*UI = Parms.UI;
}


// Function UIS_OptionTab_Audio.UIS_OptionTab_Audio_C.InitializeFocus
// (Public, BlueprintCallable, BlueprintEvent)

void UUIS_OptionTab_Audio_C::InitializeFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIS_OptionTab_Audio_C", "InitializeFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIS_OptionTab_Audio.UIS_OptionTab_Audio_C.IsOpened
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsOpen                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIS_OptionTab_Audio_C::IsOpened(bool* IsOpen)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIS_OptionTab_Audio_C", "IsOpened");

	Params::UIS_OptionTab_Audio_C_IsOpened Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsOpen != nullptr)
		*IsOpen = Parms.IsOpen;
}


// Function UIS_OptionTab_Audio.UIS_OptionTab_Audio_C.SetPreWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          PreWidget                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUIS_OptionTab_Audio_C::SetPreWidget(class UWidget* PreWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIS_OptionTab_Audio_C", "SetPreWidget");

	Params::UIS_OptionTab_Audio_C_SetPreWidget Parms{};

	Parms.PreWidget = PreWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIS_OptionTab_Audio.UIS_OptionTab_Audio_C.SetSelectedValues
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   Master                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   BGM                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   SE                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   UI                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIS_OptionTab_Audio_C::SetSelectedValues(uint8 Master, uint8 BGM, uint8 SE, uint8 UI)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIS_OptionTab_Audio_C", "SetSelectedValues");

	Params::UIS_OptionTab_Audio_C_SetSelectedValues Parms{};

	Parms.Master = Master;
	Parms.BGM = BGM;
	Parms.SE = SE;
	Parms.UI = UI;

	UObject::ProcessEvent(Func, &Parms);
}

}

