#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIS_InfoTab_Skill

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"
#include "EN_WidgetFocusDirection_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UIS_InfoTab_Skill.UIS_InfoTab_Skill_C
// 0x00A0 (0x0370 - 0x02D0)
class UUIS_InfoTab_Skill_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 IMG_SkillCan;                                      // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IMG_Top_SkillIcon;                                 // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIP_Button_Switcher_IconAndText_C*     SWT_01;                                            // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIP_Button_Switcher_IconAndText_C*     SWT_02;                                            // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIP_Button_Switcher_IconAndText_C*     SWT_03;                                            // 0x02F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIP_Button_Switcher_IconAndText_C*     SWT_04;                                            // 0x0300(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIP_Button_Switcher_IconAndText_C*     SWT_05;                                            // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIP_Button_Switcher_IconAndText_C*     SWT_06;                                            // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TX_SkillDescription;                               // 0x0318(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TX_Top_SkillLevel;                                 // 0x0320(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TX_Top_SkillName;                                  // 0x0328(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUIP_SkillLevelTuner_C*                 UIP_SkillLevelTuner;                               // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              FocusMove_DownOut;                                 // 0x0338(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              FocusMove_UpOut;                                   // 0x0348(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class UUIP_Button_Switcher_IconAndText_C*> SwitchData;                                    // 0x0358(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	int32                                         SelectSwitchIndex;                                 // 0x0368(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__UIS_InfoTab_Skill_SWT_01_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
	void BndEvt__UIS_InfoTab_Skill_SWT_02_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature();
	void BndEvt__UIS_InfoTab_Skill_SWT_03_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature();
	void BndEvt__UIS_InfoTab_Skill_SWT_04_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature();
	void BndEvt__UIS_InfoTab_Skill_SWT_05_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature();
	void BndEvt__UIS_InfoTab_Skill_SWT_06_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature();
	void BndEvt__UIS_InfoTab_Skill_UIP_SkillLevelTuner_K2Node_ComponentBoundEvent_6_OnClicked__DelegateSignature();
	void CloseWidget(bool* Success);
	void Construct();
	void ExecuteUbergraph_UIS_InfoTab_Skill(int32 EntryPoint);
	class UWidget* FocusMove_ToLevelTune(EUINavigation Navigation_0);
	class UWidget* FocusMove_ToSkillButton(EUINavigation Navigation_0);
	class UWidget* FocusMoveDownOut(EUINavigation Navigation_0);
	class UWidget* FocusMoveUpOut(EUINavigation Navigation_0);
	void GetFocusWidget(EN_WidgetFocusDirection MoveInDirection, class UWidget** FocusTargetWidget);
	void Initialize(bool IsRefreshSelectIndex);
	void InitializeFocus();
	void IsOpened(bool* IsOpen);
	void SetPreWidget(class UWidget* PreWidget);
	void ShowSkillData(int32 SelectIndex);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UIS_InfoTab_Skill_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UIS_InfoTab_Skill_C")
	}
	static class UUIS_InfoTab_Skill_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIS_InfoTab_Skill_C>();
	}
};
DUMPER7_ASSERTS_UUIS_InfoTab_Skill_C;

}

